---
title: "Exercícios Resolvidos: Matemática Financeira e Finanças"
format: html
lang: pt
date: 11/01/2025
date-format: "MMM, YYYY"
author:
  - name: Pedro Chaim
    id: pc
    email: pedro.chaim@ufsc.br
    affiliation: 
      - name: CNM/UFSC
        city: Florianópolis
        state: Santa Catarina
        url: https://cnm.ufsc.br/
---

Resoluções comentadas de exercícios selecionados sobre Matemática Financeira e Finanças em provas padronizadas e concursos públicos diversos.

Contato: [pedro.chaim@ufsc.br](mailto:pedro.chaim@ufsc.br).

## ENADE 2015

::: {#exr-enade-2015-economia-Q26}

### QUESTÃO 26

Empresas em fase de crescimento necessitam de recursos financeiros para alavancar seus projetos de expansão e, para isso, podem contar com o mercado financeiro e de capitais ao utilizar uma composição de capital próprio e/ou recursos de terceiros.

Com referência à condução da política monetária e considerando que o mercado de capitais é a principal fonte de capital próprio para as empresas e que os bancos comerciais e múltiplos são as principais instituições intermediárias entre os agentes superavitários e deficitários, avalie as afirmações a seguir.

(I) Uma política monetária contracionista reduzirá o custo do capital próprio ao aumentar a taxa livre de risco. <select name="vf" id="vf">
  <option value=""></option>
  <option value="Verdadeiro">Verdadeiro</option>
  <option value="Falso">Falso</option>
</select>
(II)  O custo do dinheiro no mercado interbancário sofrerá uma redução em função da diminuição da taxa de juros básica da economia, o que estimulará um maior nível de endividamento das empresas. <select name="vf" id="vf">
  <option value=""></option>
  <option value="Verdadeiro">Verdadeiro</option>
  <option value="Falso">Falso</option>
</select>
(III) A política monetária adotada pelo governo influencia os preços dos títulos de renda fixa quando afeta o comportamento das taxas de juros de mercado. <select name="vf" id="vf">
  <option value=""></option>
  <option value="Verdadeiro">Verdadeiro</option>
  <option value="Falso">Falso</option>
</select>
(IV)  Quando a Taxa Interna de Retorno (TIR) sofre uma redução significativa, torna-se fundamental o Banco Central adotar uma política monetária expansionista para evitar uma queda do investimento privado. <select name="vf" id="vf">
  <option value=""></option>
  <option value="Verdadeiro">Verdadeiro</option>
  <option value="Falso">Falso</option>
</select>

**É correto apenas o que se afirma em:**

(A) I e II.
(B) I e III.
(C) II e IV.
(D) I, II e IV.
(E) II, III e IV.

<label for="resposta">Sua resposta:</label>
<select name="resposta" id="altenativa">
  <option value=""></option>
  <option value="A">A</option>
  <option value="B">B</option>
  <option value="C">C</option>
  <option value="D">D</option>
  <option value="E">E</option>
</select>

::: {.callout-caution title="Resolução" collapse="true" appearance="minimal"}

> *I. Uma política monetária contracionista reduzirá o custo do capital próprio ao aumentar a taxa livre de risco.*

O **custo do capital próprio** é a remuneração requerida pelos acionistas, os donos da empresa. Acionistas só são remunerados (com dividendos) se a empresa estiver gerando lucro líquido. Credores são remunerados independentemente do lucro corrente da empresa, a menos de insolvência. Portanto o **custo do capital de terceiros** tende a ser inferior ao **custo do capital próprio**. Seria o **custo do capital de terceiros** impactado diretamente por um aumento da taxa livre de risco. Devido à relação de custo de oportunidade entre ações e ativos de dívida, um aumento na taxa livre de risco tenderia a aumentar (indiretamente) o **custo do capital próprio**. Afirmação falsa.

---

> *II. O custo do dinheiro no mercado interbancário sofrerá uma redução em função da diminuição da taxa de juros básica da economia, o que estimulará um maior nível de endividamento das empresas.*

De fato, o *custo do dinheiro no mercado interbancário* depende diretamente da *taxa de juros básica da economia*. Uma redução da taxa básica leva, então, a uma redução no custo do capital de terceiros. Mais investimentos produtivos se tornam economicamente viáveis (VPL positivo, TIR superior ao custo de capital), incentivando empresas a se endividarem e executarem tais projetos de investimento. Afirmação verdadeira.

---

> *III. A política monetária adotada pelo governo influencia os preços dos títulos de renda fixa quando afeta o comportamento das taxas de juros de mercado.*

O preço de um título de desconto (zero-cupom) é dado por

\begin{align*}
  PU = \frac{VF}{(1+y)^T},
\end{align*}

onde $VF$ é o valor de face do título, $T$ é a quantidade de períodos até o vencimento, e $y$ é a *yield to maturity*, a taxa de juros de mercado embutida no título (que tende a responder na mesma direção de mudanças na taxa básica de juros da economia). Repare que, tudo mais constante, um aumento em $y$ leva a uma redução de $PU$. Afirmação verdadeira.

---

> *IV. Quando a Taxa Interna de Retorno (TIR) sofre uma redução significativa, torna-se fundamental o Banco Central adotar uma política monetária expansionista para evitar uma queda do investimento privado.*

A Taxa Interna de Retorno (TIR) de um projeto de investimento (quando existe) é a taxa de juros que torna o Valor Presente Líquido (VPL) desse projeto zero. Portanto pode ser interpretada como o maior custo de capital para qual tal projeto de investimento ainda é economicamente viável. 

Portanto se as TIR na economia (que estão relacionadas fundamentalmente com a rentabilidade de um investimento, independentemente de como esse investimento é financiado, seja via dívida ou capital próprio) cairem como um todo, menos projetos de investimentos serão economicamente viáveis, o que leva a uma queda no fluxo de investimento privado. Ao promover uma política monetária expansionista (redução da taxa de juros básica), o banco central reduz o custo do capital de terceiros na economia, o que leva a uma redução no custo de capital (agregado) das empresas, elevando a quantidade de investimentos executados, aumentando o fluxo de investimento privado. Afirmação verdadeira.

:::

:::

## Exame ANPEC

- [Link para provas antigas e gabaritos.](https://exame.anpec.org.br/index.php?r=site/provasAnteriores)

---

### Questão 04 (ANPEC 2025 – Matemática)

::: {#exr-anpec-2025-matematica-Q04}

> Tema: Tabela price de amortização de empréstimos.

Uma dívida de $P_0>0$ reais, contraída no período $0$, é paga a partir do período subsequente em uma quantidade de prestações dada por um número par $T>0$, todas de $R$ reais, sob o sistema Price de amortização.
Assim, $P_t=(1+r)P_{t-1}-R$, $\forall, t \in {1,\ldots,T}$, e $P_T=0$; em que $P_t$ representa o saldo devedor ao fim do período $t$, e $r>0$ é a taxa de juros acordada entre as partes. Julgue as afirmativas abaixo quanto a sua veracidade:

(0) Para cada $t \in {0,1,\ldots,T}$, vale $P_t = P_0 - tP_0/T$. <select name="vf" id="vf">
  <option value=""></option>
  <option value="Verdadeiro">Verdadeiro</option>
  <option value="Falso">Falso</option>
</select>
(1) Cada prestação é de $P_0(1+r)^T/T$ reais. <select name="vf" id="vf">
  <option value=""></option>
  <option value="Verdadeiro">Verdadeiro</option>
  <option value="Falso">Falso</option>
</select>
(2) Cada prestação supera os $rP_0$ reais. <select name="vf" id="vf">
  <option value=""></option>
  <option value="Verdadeiro">Verdadeiro</option>
  <option value="Falso">Falso</option>
</select>
(3) Quanto maior $r$, maior será $R$. <select name="vf" id="vf">
  <option value=""></option>
  <option value="Verdadeiro">Verdadeiro</option>
  <option value="Falso">Falso</option>
</select>
(4) Ao fim do período $T/2$, o saldo devedor ainda corresponde a mais da metade da dívida inicial. <select name="vf" id="vf">
  <option value=""></option>
  <option value="Verdadeiro">Verdadeiro</option>
  <option value="Falso">Falso</option>
</select>

::: {.callout-caution title="Resolução" collapse="true" appearance="minimal"}
Escrevendo $\{P_t\}$ de forma recursiva (tomando $P_0$ como dado), temos
\begin{align*}
  P_1 &= (1+r)P_0 - R
\end{align*}

\begin{align*}
  P_2 &= (1+r)P_1 - R \\&= (1+r)[(1+r)P_0-R]-R \\&= (1+r)^2P_0 - R[1 + (1+r)]
\end{align*}

\begin{align*}
  P_3 &= (1+r)P_2 - R \\&=(1+r)^3 - R[1 + (1+r) + (1+r)^2]
\end{align*}

Conseguimos então perceber que
\begin{align*}
  P_t &= (1+r)^tP_0 - R[1+(1+r)+(1+r)^2+\cdots+(1+r)^{t-1}]
\end{align*}

Chame $(1+r)=q$, a expressão entre colchetes acima, que é a soma parcial de uma progressão geométrica com $n$ elementos (o expoente máximo é $n-1$) fica
\begin{align*}
  S_{n-1} = 1 + q + q^2 + \cdots + q^{n-1}
\end{align*}
Faça 
\begin{align*}
  S_{n-1}-qS_{n-1} &= 1-q^n \\
  S_{n-1} &= \frac{1-q^n}{1-q}
\end{align*}

Substituindo $q=(1+r)$ temos
\begin{align*}
  \frac{1-(1+r)^t}{1-(1+r)}=\frac{(1+r)^t-1}{r}
\end{align*}

Então

\begin{align*}
  P_t = (1+r)^tP_0-R\left(\frac{(1+r)^t-1}{r}\right)
\end{align*}

Sabemos que o saldo devedor é quitado no período $t=T$, tal que $P_T=0$. Então
\begin{align*}
  0 = (1+r)^TP_0-R\left(\frac{(1+r)^T-1}{r}\right)
\end{align*}

Resolvendo para $R$, temos

\begin{align*}
  R = P_0 \cdot r \cdot \left( \frac{(1+r)^T}{(1+r)^T-1}\right)
\end{align*}

---

> *0. Para cada $t \in {0,1,\ldots,T}$, vale $P_t = P_0 - tP_0/T$.*

Afirmação falsa, nós calcluamos 
\begin{align*}
  P_t = (1+r)^tP_0-R\left(\frac{(1+r)^t-1}{r}\right)
\end{align*}

---

> *1. Cada prestação é de $P_0(1+r)^T/T$ reais.*

Afirmação também falsa, calculamos a prestação $R$ como
\begin{align*}
  R = P_0 \cdot r \cdot \left( \frac{(1+r)^T}{(1+r)^T-1}\right)
\end{align*}

---

> *2. Cada prestação supera os $rP_0$ reais.*

Essa afirmação é verdadeira. Intuitivamente, $rP_0$ é o juro acumulado sobre o principal $P_0$ entre $t=0$ e $t=1$. Se a prestação fosse $rP_0$, o saldo devedor $P_t$ se manteria constante no tempo e a dívida nunca seria quitada. Faça $P_t=P_{t-1}$:
\begin{align*}
  P &= (1+r)P-R \\
  P-P-rP &= -R \\
  R &= rP
\end{align*}

Conseguimos também ver isso diretamente da expressão para $R$. Tome 
\begin{align*}
  R = P_0 \cdot r \cdot \left( \frac{(1+r)^T}{(1+r)^T-1}\right)
\end{align*}
Agora multiplique por $(1+r)^{-T}/(1+r)^{-T}$. Ficamos com
\begin{align*}
  R = P_0 \cdot r \cdot \left( \frac{1}{1-(1+r)^{-T}}\right)
\end{align*}

Se $(1+r)>1$, então $(1+r)^{-k}<1$, para $k=1,2,3,\dots$. Portanto 
\begin{align*}
\left( \frac{1}{1-(1+r)^{-T}}\right) > 1, \text{ e } R>rP_0
\end{align*}

---

> *3. Quanto maior $r$, maior será $R$.*

Afirmação verdadeira. Claro que, fixada a duração $T$, quanto maior a taxa de juros de um financiamento, maior será a parcela necessária para quitar o saldo devedor. 

A rígor, deveríamos calcular $dR/dr$ e mostrar que se $r>0$ e $P_0>0$ então $dR/dr>0$.

---

> *4 Ao fim do período $T/2$, o saldo devedor ainda corresponde a mais da metade da dívida inicial.*

Esse é, de longe, o item mais difícil da questão. 

Se a afirmação é verdadeira, então

\begin{align*}
  P_{T/2} > (1/2)P_0.
\end{align*}

Equivalentemente, se

\begin{align*}
  2\frac{P_{T/2}}{P_0}>1.
\end{align*}

Ou, ainda,

\begin{align*}
  2\frac{P_{T/2}}{P_0}-1>0.
\end{align*}

É a desigualdade acima que iremos julgar.




Agora lembre que, porque $P_T=0$, sabemos que $R=P_0\cdot r \cdot (1-(1+r)^{-T})^{-1}$. Esse é o valor da prestação fixa que zera o saldo devedor $P_t$ exatamente no período $t=T$.

Substituindo na fórmula para $P_t$,
\begin{align*}
  P_t = (1+r)^tP_0 - P_0\cdot r \cdot \left(\frac{(1+r)^T}{(1+r)^T-1}\right)\left(\frac{(1+r)^t-1}{r}\right)
\end{align*}

Depois de algumas manipulações conseguimos escrever

\begin{align*}
  \frac{P_t}{P_0} = \frac{(1+r)^T-(1+r)^t}{(1+r)^T-1}.
\end{align*}

Fazendo $t=T/2$ e multiplicando por $2$,

\begin{align*}
  \frac{2P_{T/2}}{P_0} = 2\left(\frac{(1+r)^T-(1+r)^{T/2}}{(1+r)^T-1}\right).
\end{align*}

Chame $(1+r)^{T/2}=x$

\begin{align*}
  \frac{2P_{T/2}}{P_0} &= 2\left(\frac{x^2-x}{x^2-1}\right) \\
  &= 2x \left(\frac{x-1}{(x+1)(x-1)}\right) \\
  &= 2x \left(\frac{1}{x+1}\right)
\end{align*}

Então,

\begin{align*}
  \frac{2P_{T/2}}{P_0}-1 &= 2x \left(\frac{1}{x+1}\right)-1 \\
  &= \frac{2x-(x+1)}{x+1} = \frac{x-1}{x+1}
\end{align*}

Lembrando que a afirmação é verdadeira se $\dfrac{2P_{T/2}}{P_0}-1>0$, e que $x=(1+r)^{T/2}>1$. Como $x>1$, a desigualdade abaixo vale.

\begin{align*}
\frac{x-1}{x+1} > 0
\end{align*}



Afirmação verdadeira.

:::

:::

### Questão 10 (ANPEC 2025 – Matemática)

::: {#exr-anpec-2025-matematica-Q10}

> Tema: Equações em diferenças.

Considere o contexto em que um investimento inicial de $A>0$ unidades monetárias pode ser aplicado, no período inicial $t=0$, em apenas um dentre dois ativos disponíveis.

O primeiro ativo remunera a uma taxa de juros $r>0$ e, devido a custos operacionais, deduz do saldo um valor $B_t$ em cada período $t=0,1,2,\ldots$. Ainda, dada uma aplicação inicial $x_0$ igual a $A>0$, o valor no instante $t+1$ satisfaz $x_{t+1}=(1+r)x_t-B_t$, onde $\forall t\geq 0$, $B_{t+1}=\left(\frac{1+r}{2}\right)B_t$ e $B_0=\frac{A}{2}$.

Com respeito ao segundo ativo, uma mesma aplicação inicial $y_0$ em $t=0$ igual a $A>0$ implica um valor $y_{t+1}$ no período $t+1$ que satisfaz $y_{t+1}=(1+\bar r)y_t$, onde $\bar r>0$.

Sabendo que $\frac{1+r}{1+\bar r}=V\geq 0$ e $\lim_{t\rightarrow\infty}\frac{x_t}{y_t}=\frac{1}{2}$, determine o valor de $V$.

::: {.callout-caution title="Resolução" collapse="true" appearance="minimal"}

\begin{align*}
  B_1 &= \left(\frac{1+r}{2}\right)B_0\\
  B_2 &= \left(\frac{1+r}{2}\right)B_1 = \left(\frac{1+r}{2}\right)^2B_0 
\end{align*}

Generalizando,

\begin{align*}
  B_t = \left(\frac{1+r}{2}\right)^tB_0
\end{align*}

\begin{align*}
  x_t = (1+r)x_{t-1}-B_{t-1}
\end{align*}

\begin{align*}
  x_t = (1+r)x_{t-1}-\left(\frac{1+r}{2}\right)^{t-1}B_0
\end{align*}

Com $(1+r)=a$, também, faça $(a/2)=q$.

\begin{align*}
  x_t = ax_{t-1}-q^{t-1}B_0
\end{align*}


\begin{align*}
  x_1 &= ax_0-q^{1-1}B_0\\
  &= ax_0-B_0
\end{align*}

\begin{align*}
  x_2 &= ax_1 - B_1 \\
  &= a(ax_0-B_0) - qB_0 \\
  &= a^2x_0 - aB_0 - qB_0
\end{align*}

\begin{align*}
  x_3 &= ax_2 - B_2 \\
  &=  a(a^2x_0-aB_0-qB_0)-q^2B_0 \\
  &= a^3x_0 - a^2B_0 - aqB_0 - q^2B_0
\end{align*}

\begin{align*}
  x_4 &= ax_3 - B_3 \\
  &= a(a^3x_0 - a^2B_0 - aqB_0 - q^2B_0) - q^3B_0 \\
  &= a^4x_0 - (a^3 + a^2q + aq^2 + q^3)B_0
\end{align*}

\begin{align*}
  x_5 &= ax_4 - B_4 \\
  &= a^5 x_0 - B_0(a^4 + a^3q + a^2q^2 + aq^3 + q^4)
\end{align*}

Perceba que a expressão entre parênteses é

\begin{align*}
  S_n = \sum_{j=1}^n a^{n-j}q^j
\end{align*}

Faça $a^{-n}S_n$:

\begin{align*}
  a^{-n}S_n = a^{-n}\sum_{j=0}^n a^{n-j}q^j=\sum_{j=0}^n a^{-j}q^j = \sum^n_{j=0}(q/a)^j
\end{align*}

\begin{align*}
  a^{-n}S_n &= 1 + p + p^2 + \cdots + p^n \\
  pa^{-n}S_n &= p + p + p^2 + \cdots + p^n + p^{n+1}
\end{align*}

Então

\begin{align*}
  a^{-n}S_n-pa^{-n}S_n = 1-p^{n+1} \\
  S_na^{-n}(1-p) = 1-p^{n+1}
\end{align*}

\begin{align*}
  S_n = a^n\left(\frac{1-p^{n+1}}{1-p}\right)
\end{align*}

\begin{align*}
  S_n = a^n\left(\frac{1-p^{n+1}}{1-p}\right)
\end{align*}

Mas $q=a/2$, então 

\begin{align*}
  p = \frac{a/2}{a/1} = 1/2
\end{align*}

E

\begin{align*}
  S_n &= a^n \left( \frac{1-(1/2)^{n+1}}{1-1/2} \right) \\
  &= 2a^n \left(2-(1/2)^{n+1}\right)
\end{align*}

Então

\begin{align*}
  x_t &= a^tx_0 + B_0 S_{t-1} \\
  &= a^t x_0 + B_0 a^{t-1}(1-(1/2)^n) \\
  &= a^t x_0 + a^tB_0a^{-1}(1-(1/2)^n)
\end{align*}

E $x_0=A$ e $B_0=A/2$

\begin{align*}
  x_t &= a^tA + a^t(A/2)a^{-1}(1-(1/2)^n) \\
  & = \frac{2a^tA + a^tAa^{-1}(1-(1/2)^n)}{2}
\end{align*}

:::

:::


## Concursos Públicos

- Concurso Banco Central 2024, Cargo: Analista - Economia e Finanças. 
  - [Link para a prova.](https://arq.pciconcursos.com.br/provas/33165042/5cc924e9beef/analista_Economia_e_financas.pdf)
  - [Link para o gabarito oficial.](https://arq.pciconcursos.com.br/provas/33165042/68c6775a2364/gabarito.pdf)

### Questão 77 (Banco Central 2024, Cargo: Analista - Economia e Finanças)
  
::: {#exr-bc-2024-Q77}

Acerca dos títulos emitidos pelo Tesouro Nacional, julgue os itens seguintes.

(79)  O valor investido no título Tesouro Prefixado 2031 pode ser resgatado a qualquer data, com a garantia da taxa de juros contratada no dia da compra.
(80)  O rendimento dos títulos Tesouro IPCA corresponde a uma taxa prefixada de juros somada à variação do índice nacional de preços ao consumidor amplo (IPCA) no período.

No que se refere ao mercado de ações, julgue os itens a seguir.

(81)  O valor de mercado de uma ação coincide com o seu valor intrínseco, por corresponder às expectativas de fluxos de ganhos futuros.
(82)  Enquanto ações ordinárias dão direito apenas a voto, as ações preferenciais dão direito à parte dos dividendos proporcional ao número de votos detidos pelo acionista.

Considerando que o preço de mercado de uma ação esteja em **R$ 195,00**, julgue o próximo item, referente ao mercado de opções.

(83)  No referido contexto, o titular de opções de venda da referida ação poderá vendê-la por **R$ 200,00** e, com isso, terá ganho igual a **R$ 5,00**, descontado o prêmio pago pelas opções.

::: {.callout-caution title="Resolução" collapse="true" appearance="minimal"}

> *79. O valor investido no título Tesouro Prefixado 2031 pode ser resgatado a qualquer data, com a garantia da taxa de juros contratada no dia da compra.*

Falso. É possível vender o Tesouro Prefixado antes do vencimento, mas sem garantia da taxa contratada — o preço oscila conforme as taxas de mercado (marcação a mercado).

---

> *80.  O rendimento dos títulos Tesouro IPCA corresponde a uma taxa prefixada de juros somada à variação do índice nacional de preços ao consumidor amplo (IPCA) no período.*

Verdadeiro. O Tesouro IPCA rende taxa real prefixada + variação do IPCA do período.

---

> *81.  O valor de mercado de uma ação coincide com o seu valor intrínseco, por corresponder às expectativas de fluxos de ganhos futuros.*

Falso. O preço de mercado de uma ação resulta de oferta e demanda e pode divergir do “valor intrínseco” (valor presente dos fluxos esperados). É formado pela expectativa conjunta dos agentes do mercado acerca dos fluxos futuros de dividendos.

---

> *82. Enquanto ações ordinárias dão direito apenas a voto, as ações preferenciais dão direito à parte dos dividendos proporcional ao número de votos detidos pelo acionista.*

Falso. Ações ordinárias têm direito a voto (e também a dividendos); ações preferenciais geralmente têm prioridade em dividendos e, em situações usuais, não têm direito voto na assembéia dos acionistas. Dividendos são proporcionais ao número de ações, não de votos.

---

> *Considerando que o preço de mercado de uma ação esteja em **R$ 195,00**, julgue o próximo item, referente ao mercado de opções.*

> *83. No referido contexto, o titular de opções de venda da referida ação poderá vendê-la por **R\$ 200,00** e, com isso, terá ganho igual a **R\$ 5,00**, descontado o prêmio pago pelas opções.*

Verdadeiro. Se eu detenho uma opção de venda com strike $K=200$ e o preço de mercado da ação é $S=195$, e eu exercer tal opção (o equivalente a vender minha ação ao emissor pelo preço $K$), o resultado líquido é $K-S=5$, não considerando o prêmio pago pela opção de venda.

:::

:::

## Certificações Anbima CPA

- [Link para fonte das questões](https://www.anbima.com.br/data/files/DF/86/EE/B6/EB6F8910C03A3F89B82BA2A8/Caderno-de-questoes-CPA.pdf)

### Questão 2 

::: {#exr-anbima-CPA-Q02}


**Contexto:**

Paulo pediu ao seu gerente duas opções de investimento com um horizonte de 360 dias para aplicar R$ 1.000,00. O gerente apresentou-lhe um CDB de instituição de grande porte com prazo de 1 ano e taxa de remuneração bruta de 12% a.a. A segunda opção foi um Certificado de Operações Estruturadas (COE) com exposição ao Índice Ibovespa (IBOV), também com prazo de 1 ano. O COE tem a seguinte estrutura de retornos:

| Valor do IBOV em um ano                         | Valor retornado aos investidores em um ano         |
| ----------------------------------------------- | -------------------------------------------------- |
| Menor ou igual que 125.000                      | R$ 1.000,00                                        |
| Maior que 125.000 e abaixo ou igual que 145.000 | 1.000 * [1 + (IBOV − 125.000) / 125.000]           |
| Acima de 145.000 e abaixo ou igual de 153.700   | 1.000 * [1,16 + 0,75 * (IBOV − 145.000) / 145.000] |
| Acima de 153.700                                | 1.000 * 1,205                                      |

**Enunciado:**

Com base nos aspectos apresentados e nas características dos produtos, a análise correta sobre
o investimento de Paulo é:

(A) Para que o COE apresente remuneração bruta superior ao CDB, o índice deve atingir ou
superar 140.000 pontos.
(B) Caso o índice Ibovespa atinja 160.000 em um ano, a rentabilidade líquida de impostos do
COE será de 17,425%.
(C) A tributação do imposto de renda incidente sobre o retorno do COE é inferior àquele
incidente sobre o CDB.
(D) O COE, assim como o CDB, são produtos cobertos pelo Fundo Garantidor de Créditos (FGC).

::: {.callout-caution title="Resolução" collapse="true" appearance="minimal"}

Um Certificado de Depósito Bancário (CDB) é um tipo de investimento de renda fixa bastante popular no Brasil em que você "empresta" dinheiro para uma instituição bancária em troca de juros. Condições de remuneração (pré ou pós-fixado) e de liquidez dependem do acordo entre a instituição bancária emitente e o detentor do CDB. Os CDB são cobertos pelo FGC (fundo garantidor de crédito).

Um Certificado de Operações Estruturadas (COE) é um produto financeiro de renda fixa, cuja remuneração (similarmente a um derivativo) é contingente ao valor de um ou mais diferentes ativos. Esses ativos podem ser ações, moedas, taxas de juro, etc. É comum que um COE defina perdas e ganhos máximos frente bandas de variação do preço dos "ativos objeto". Os COE não são cobertos pelo FGC.

A tributação IR de ambos CDB e COE segue a tabela regressiva abaixo. 

| Prazo do Investimento              | Alíquota de IR sobre os Rendimentos |
| ---------------------------------- | ----------------------------------- |
| Até 180 dias                       | 22,5%                               |
| De 181 a 360 dias                  | 20,0%                               |
| De 361 a 720 dias                  | 17,5%                               |
| Acima de 720 dias (mais de 2 anos) | 15,0%                               |



---

> *A. Para que o COE apresente remuneração bruta superior ao CDB, o índice deve atingir ou
superar 140.000 pontos.*

A rentabilidade bruta do CDB pré-fixado do enunciado é sempre 12\% ao ano.

Se o Ibovespa atingir 140000 pontos, o valor retornado ao investidor pelo COE é

\begin{align*}
  R\$ 1000\times\left(1+\frac{140000-125000}{125000}\right)
\end{align*}

Precisamos fazer a divisão acima:

\begin{align*}
  140-125 = 15
\end{align*}
\begin{align*}
  \frac{15}{125} &= \frac{1}{10}\frac{150}{125}\\
  &=\frac{1}{10}\frac{6}{5}\\
  &=0{,}1\times 1{,}2=0{,}12
\end{align*}

Portanto o valor retornado ao investidor seria
\begin{align*}
  R\$ 1000\times(1+0{,}12) = R\$ 1120
\end{align*}

Calculando o retorno como $(S_1-S_0)/S_0$ vemos que, se o índice Ibovespa atingir 140000 pontos, o retorno bruto do investidor é exatamente 12\%. 

Então se o índice Ibovespa superar 140000 pontos, a remuneração bruta do COE é superior à remuneração bruta do CDB. Mas se o índice Ibovespa atingir exatamente 140000 pontos, ambas remunerações são idênticas. Logo: *"Para que o COE apresente remuneração bruta **superior** ao CDB, o índice deve **superar** 140000 pontos."*

Eu diria que a afirmativa é falsa. No gabarito oficial essa afirmação é considerada correta.

---

> *B.  Caso o índice Ibovespa atinja 160.000 em um ano, a rentabilidade líquida de impostos do
COE será de 17,425%.*

Se o índice Ibovespa atingir 160.000 pontos ao final do ano, o valor bruto retornado ao investidor no COE é $R\$1205$.

Como o prazo do investimento é 360 dias, a alíquota relevante é 20\%.

Portanto o imposto pago seria

\begin{align*}
  (R\$1205-R\$1000)\times 0.2 = R\$41
\end{align*}

O rendimento líquido seria $R\$1205-R\$41 = R\$1164$, resultando em um retorno líquido de $16{,4}\%$. Afirmação falsa.

---

> *C. A tributação do imposto de renda incidente sobre o retorno do COE é inferior àquele incidente sobre o CDB.*

Afirmação falsa. Ambos os investimentos têm o mesmo prazo e mesma tabela de IR, a tributação é a mesma.

---

> *D. O COE, assim como o CDB, são produtos cobertos pelo Fundo Garantidor de Créditos (FGC).*

Afirmação falsa. Dentre esses ativos, apenas o CDB é coberto pelo FGC.

:::

:::

### Questão 9

::: {#exr-anbima-CPA-Q09}

Lucas é um investidor conservador que busca preservar seu capital enquanto ganha um retorno constante. Ele tem algumas economias e deseja investir em títulos públicos. Lucas está particularmente preocupado com a inflação e quer garantir que seu investimento mantenha seu poder de compra ao longo do tempo, mesmo no caso de uma disparada inflacionária.

**Enunciado**

Lucas buscou orientação de seu gerente, que, considerando seu perfil, sugeriu que ele investisse em:

(A) NTN-B.
(B) LTN.
(C) CDB.
(D) LCA.

::: {.callout-caution title="Resolução" collapse="true" appearance="minimal"}

Lucas busca "preservar seu capital enquanto ganha um retorno constante", "investir em títulos públicos", e "está particularmente preocupado com a inflação".

[Descrição dos títulos emitidos pelo Tesouro](https://www.tesourodireto.com.br/produtos/nossos-produtos)

---

A NTN-B (Nota do Tesouro Nacional Série B), ou Tesouro IPCA+ com Juros Semestrais, é um título de renda fixa emitido pelo Tesouro nacional cuja remuneração é composta por uma parte pré-fixada (garantida no momento da compra), mais a variação do índice IPCA. Essa seria a indicação adequada.

---

A LTN (Letra do Tesouro Nacional), ou Tesouro Prefixado, é um título pré-fixado zero-cupom. No momento da compra o detentor paga o PU (que depende da *yield to maturity* implícita) e no vencimento recebe o valor de face de R$1000. Não seria uma indicação adequada porque não protege contra a inflação.

---

Certificados de Depósito Bancário (CDB) é um tipo de investimento de renda fixa bastante popular no Brasil em que você "empresta" dinheiro para uma instituição bancária em troca de juros. Condições de remuneração (pré ou pós-fixado) e de liquidez dependem do acordo entre a instituição bancária emitente e o detentor do CDB. Os CDB são cobertos pelo FGC (fundo garantidor de crédito). Não seria uma indicação adequada porque nem sempre sua remuneração é vínculada à inflação, e porque não é um título público.

---

Letras de Crédito do Agronegócio são títulos de renda fixa emitidos por instituições privadas cujos recursos são redirecionados para crédito a atividades agrícolas. Atualmente as LCA são isentas de imposto de renda. Não seria uma indicação adequada porque nem sempre sua remuneração é vínculada à inflação, e porque não é um título público.

:::

:::