<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Pedro Chaim">

<title>Exercícios Resolvidos: Matemática Financeira e Finanças – ESAG_2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-1fe81d0376b2c50856e68e651e390326.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">ESAG_2025</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./questoes_estatistica.html"> 
<span class="menu-text">Estatística</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./questoes_matematica_financeira.html" aria-current="page"> 
<span class="menu-text">Matemática Financeira</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#enade-2015" id="toc-enade-2015" class="nav-link active" data-scroll-target="#enade-2015">ENADE 2015</a></li>
  <li><a href="#exame-anpec" id="toc-exame-anpec" class="nav-link" data-scroll-target="#exame-anpec">Exame ANPEC</a>
  <ul class="collapse">
  <li><a href="#questão-04-anpec-2025-matemática" id="toc-questão-04-anpec-2025-matemática" class="nav-link" data-scroll-target="#questão-04-anpec-2025-matemática">Questão 04 (ANPEC 2025 – Matemática)</a></li>
  <li><a href="#questão-10-anpec-2025-matemática" id="toc-questão-10-anpec-2025-matemática" class="nav-link" data-scroll-target="#questão-10-anpec-2025-matemática">Questão 10 (ANPEC 2025 – Matemática)</a></li>
  </ul></li>
  <li><a href="#concursos-públicos" id="toc-concursos-públicos" class="nav-link" data-scroll-target="#concursos-públicos">Concursos Públicos</a>
  <ul class="collapse">
  <li><a href="#questão-77-banco-central-2024-cargo-analista---economia-e-finanças" id="toc-questão-77-banco-central-2024-cargo-analista---economia-e-finanças" class="nav-link" data-scroll-target="#questão-77-banco-central-2024-cargo-analista---economia-e-finanças">Questão 77 (Banco Central 2024, Cargo: Analista - Economia e Finanças)</a></li>
  </ul></li>
  <li><a href="#certificações-anbima-cpa" id="toc-certificações-anbima-cpa" class="nav-link" data-scroll-target="#certificações-anbima-cpa">Certificações Anbima CPA</a>
  <ul class="collapse">
  <li><a href="#questão-2" id="toc-questão-2" class="nav-link" data-scroll-target="#questão-2">Questão 2</a></li>
  <li><a href="#questão-9" id="toc-questão-9" class="nav-link" data-scroll-target="#questão-9">Questão 9</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exercícios Resolvidos: Matemática Financeira e Finanças</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Autor</div>
  <div class="quarto-title-meta-heading">Afiliação</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Pedro Chaim <a href="mailto:pedro.chaim@ufsc.br" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            <a href="https://cnm.ufsc.br/">
            CNM/UFSC
            </a>
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">nov, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Resoluções comentadas de exercícios selecionados sobre Matemática Financeira e Finanças em provas padronizadas e concursos públicos diversos.</p>
<p>Contato: <a href="mailto:pedro.chaim@ufsc.br">pedro.chaim@ufsc.br</a>.</p>
<section id="enade-2015" class="level2">
<h2 class="anchored" data-anchor-id="enade-2015">ENADE 2015</h2>
<div id="exr-enade-2015-economia-Q26" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercício 1 (QUESTÃO 26)</strong></span> Empresas em fase de crescimento necessitam de recursos financeiros para alavancar seus projetos de expansão e, para isso, podem contar com o mercado financeiro e de capitais ao utilizar uma composição de capital próprio e/ou recursos de terceiros.</p>
<p>Com referência à condução da política monetária e considerando que o mercado de capitais é a principal fonte de capital próprio para as empresas e que os bancos comerciais e múltiplos são as principais instituições intermediárias entre os agentes superavitários e deficitários, avalie as afirmações a seguir.</p>
<ol type="I">
<li>Uma política monetária contracionista reduzirá o custo do capital próprio ao aumentar a taxa livre de risco. <select name="vf" id="vf"> <option value=""></option> <option value="Verdadeiro">Verdadeiro</option> <option value="Falso">Falso</option> </select></li>
<li>O custo do dinheiro no mercado interbancário sofrerá uma redução em função da diminuição da taxa de juros básica da economia, o que estimulará um maior nível de endividamento das empresas. <select name="vf" id="vf"> <option value=""></option> <option value="Verdadeiro">Verdadeiro</option> <option value="Falso">Falso</option> </select></li>
<li>A política monetária adotada pelo governo influencia os preços dos títulos de renda fixa quando afeta o comportamento das taxas de juros de mercado. <select name="vf" id="vf"> <option value=""></option> <option value="Verdadeiro">Verdadeiro</option> <option value="Falso">Falso</option> </select></li>
<li>Quando a Taxa Interna de Retorno (TIR) sofre uma redução significativa, torna-se fundamental o Banco Central adotar uma política monetária expansionista para evitar uma queda do investimento privado. <select name="vf" id="vf"> <option value=""></option> <option value="Verdadeiro">Verdadeiro</option> <option value="Falso">Falso</option> </select></li>
</ol>
<p><strong>É correto apenas o que se afirma em:</strong></p>
<ol type="A">
<li>I e II.</li>
<li>I e III.</li>
<li>II e IV.</li>
<li>I, II e IV.</li>
<li>II, III e IV.</li>
</ol>
<p><label for="resposta">Sua resposta:</label> <select name="resposta" id="altenativa"> <option value=""></option> <option value="A">A</option> <option value="B">B</option> <option value="C">C</option> <option value="D">D</option> <option value="E">E</option> </select></p>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Resolução">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Cuidado</span>Resolução
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p><em>I. Uma política monetária contracionista reduzirá o custo do capital próprio ao aumentar a taxa livre de risco.</em></p>
</blockquote>
<p>O <strong>custo do capital próprio</strong> é a remuneração requerida pelos acionistas, os donos da empresa. Acionistas só são remunerados (com dividendos) se a empresa estiver gerando lucro líquido. Credores são remunerados independentemente do lucro corrente da empresa, a menos de insolvência. Portanto o <strong>custo do capital de terceiros</strong> tende a ser inferior ao <strong>custo do capital próprio</strong>. Seria o <strong>custo do capital de terceiros</strong> impactado diretamente por um aumento da taxa livre de risco. Devido à relação de custo de oportunidade entre ações e ativos de dívida, um aumento na taxa livre de risco tenderia a aumentar (indiretamente) o <strong>custo do capital próprio</strong>. Afirmação falsa.</p>
<hr>
<blockquote class="blockquote">
<p><em>II. O custo do dinheiro no mercado interbancário sofrerá uma redução em função da diminuição da taxa de juros básica da economia, o que estimulará um maior nível de endividamento das empresas.</em></p>
</blockquote>
<p>De fato, o <em>custo do dinheiro no mercado interbancário</em> depende diretamente da <em>taxa de juros básica da economia</em>. Uma redução da taxa básica leva, então, a uma redução no custo do capital de terceiros. Mais investimentos produtivos se tornam economicamente viáveis (VPL positivo, TIR superior ao custo de capital), incentivando empresas a se endividarem e executarem tais projetos de investimento. Afirmação verdadeira.</p>
<hr>
<blockquote class="blockquote">
<p><em>III. A política monetária adotada pelo governo influencia os preços dos títulos de renda fixa quando afeta o comportamento das taxas de juros de mercado.</em></p>
</blockquote>
<p>O preço de um título de desconto (zero-cupom) é dado por</p>
<p><span class="math display">\[\begin{align*}
  PU = \frac{VF}{(1+y)^T},
\end{align*}\]</span></p>
<p>onde <span class="math inline">\(VF\)</span> é o valor de face do título, <span class="math inline">\(T\)</span> é a quantidade de períodos até o vencimento, e <span class="math inline">\(y\)</span> é a <em>yield to maturity</em>, a taxa de juros de mercado embutida no título (que tende a responder na mesma direção de mudanças na taxa básica de juros da economia). Repare que, tudo mais constante, um aumento em <span class="math inline">\(y\)</span> leva a uma redução de <span class="math inline">\(PU\)</span>. Afirmação verdadeira.</p>
<hr>
<blockquote class="blockquote">
<p><em>IV. Quando a Taxa Interna de Retorno (TIR) sofre uma redução significativa, torna-se fundamental o Banco Central adotar uma política monetária expansionista para evitar uma queda do investimento privado.</em></p>
</blockquote>
<p>A Taxa Interna de Retorno (TIR) de um projeto de investimento (quando existe) é a taxa de juros que torna o Valor Presente Líquido (VPL) desse projeto zero. Portanto pode ser interpretada como o maior custo de capital para qual tal projeto de investimento ainda é economicamente viável.</p>
<p>Portanto se as TIR na economia (que estão relacionadas fundamentalmente com a rentabilidade de um investimento, independentemente de como esse investimento é financiado, seja via dívida ou capital próprio) cairem como um todo, menos projetos de investimentos serão economicamente viáveis, o que leva a uma queda no fluxo de investimento privado. Ao promover uma política monetária expansionista (redução da taxa de juros básica), o banco central reduz o custo do capital de terceiros na economia, o que leva a uma redução no custo de capital (agregado) das empresas, elevando a quantidade de investimentos executados, aumentando o fluxo de investimento privado. Afirmação verdadeira.</p>
</div>
</div>
</div>
</div>
</section>
<section id="exame-anpec" class="level2">
<h2 class="anchored" data-anchor-id="exame-anpec">Exame ANPEC</h2>
<ul>
<li><a href="https://exame.anpec.org.br/index.php?r=site/provasAnteriores">Link para provas antigas e gabaritos.</a></li>
</ul>
<hr>
<section id="questão-04-anpec-2025-matemática" class="level3">
<h3 class="anchored" data-anchor-id="questão-04-anpec-2025-matemática">Questão 04 (ANPEC 2025 – Matemática)</h3>
<div id="exr-anpec-2025-matematica-Q04" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercício 2</strong></span> &nbsp;</p>
<blockquote class="blockquote">
<p>Tema: Tabela price de amortização de empréstimos.</p>
</blockquote>
<p>Uma dívida de <span class="math inline">\(P_0&gt;0\)</span> reais, contraída no período <span class="math inline">\(0\)</span>, é paga a partir do período subsequente em uma quantidade de prestações dada por um número par <span class="math inline">\(T&gt;0\)</span>, todas de <span class="math inline">\(R\)</span> reais, sob o sistema Price de amortização. Assim, <span class="math inline">\(P_t=(1+r)P_{t-1}-R\)</span>, <span class="math inline">\(\forall, t \in {1,\ldots,T}\)</span>, e <span class="math inline">\(P_T=0\)</span>; em que <span class="math inline">\(P_t\)</span> representa o saldo devedor ao fim do período <span class="math inline">\(t\)</span>, e <span class="math inline">\(r&gt;0\)</span> é a taxa de juros acordada entre as partes. Julgue as afirmativas abaixo quanto a sua veracidade:</p>
<ol start="0" type="1">
<li>Para cada <span class="math inline">\(t \in {0,1,\ldots,T}\)</span>, vale <span class="math inline">\(P_t = P_0 - tP_0/T\)</span>. <select name="vf" id="vf"> <option value=""></option> <option value="Verdadeiro">Verdadeiro</option> <option value="Falso">Falso</option> </select></li>
<li>Cada prestação é de <span class="math inline">\(P_0(1+r)^T/T\)</span> reais. <select name="vf" id="vf"> <option value=""></option> <option value="Verdadeiro">Verdadeiro</option> <option value="Falso">Falso</option> </select></li>
<li>Cada prestação supera os <span class="math inline">\(rP_0\)</span> reais. <select name="vf" id="vf"> <option value=""></option> <option value="Verdadeiro">Verdadeiro</option> <option value="Falso">Falso</option> </select></li>
<li>Quanto maior <span class="math inline">\(r\)</span>, maior será <span class="math inline">\(R\)</span>. <select name="vf" id="vf"> <option value=""></option> <option value="Verdadeiro">Verdadeiro</option> <option value="Falso">Falso</option> </select></li>
<li>Ao fim do período <span class="math inline">\(T/2\)</span>, o saldo devedor ainda corresponde a mais da metade da dívida inicial. <select name="vf" id="vf"> <option value=""></option> <option value="Verdadeiro">Verdadeiro</option> <option value="Falso">Falso</option> </select></li>
</ol>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Resolução">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Cuidado</span>Resolução
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Escrevendo <span class="math inline">\(\{P_t\}\)</span> de forma recursiva (tomando <span class="math inline">\(P_0\)</span> como dado), temos <span class="math display">\[\begin{align*}
  P_1 &amp;= (1+r)P_0 - R
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  P_2 &amp;= (1+r)P_1 - R \\&amp;= (1+r)[(1+r)P_0-R]-R \\&amp;= (1+r)^2P_0 - R[1 + (1+r)]
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  P_3 &amp;= (1+r)P_2 - R \\&amp;=(1+r)^3 - R[1 + (1+r) + (1+r)^2]
\end{align*}\]</span></p>
<p>Conseguimos então perceber que <span class="math display">\[\begin{align*}
  P_t &amp;= (1+r)^tP_0 - R[1+(1+r)+(1+r)^2+\cdots+(1+r)^{t-1}]
\end{align*}\]</span></p>
<p>Chame <span class="math inline">\((1+r)=q\)</span>, a expressão entre colchetes acima, que é a soma parcial de uma progressão geométrica com <span class="math inline">\(n\)</span> elementos (o expoente máximo é <span class="math inline">\(n-1\)</span>) fica <span class="math display">\[\begin{align*}
  S_{n-1} = 1 + q + q^2 + \cdots + q^{n-1}
\end{align*}\]</span> Faça <span class="math display">\[\begin{align*}
  S_{n-1}-qS_{n-1} &amp;= 1-q^n \\
  S_{n-1} &amp;= \frac{1-q^n}{1-q}
\end{align*}\]</span></p>
<p>Substituindo <span class="math inline">\(q=(1+r)\)</span> temos <span class="math display">\[\begin{align*}
  \frac{1-(1+r)^t}{1-(1+r)}=\frac{(1+r)^t-1}{r}
\end{align*}\]</span></p>
<p>Então</p>
<p><span class="math display">\[\begin{align*}
  P_t = (1+r)^tP_0-R\left(\frac{(1+r)^t-1}{r}\right)
\end{align*}\]</span></p>
<p>Sabemos que o saldo devedor é quitado no período <span class="math inline">\(t=T\)</span>, tal que <span class="math inline">\(P_T=0\)</span>. Então <span class="math display">\[\begin{align*}
  0 = (1+r)^TP_0-R\left(\frac{(1+r)^T-1}{r}\right)
\end{align*}\]</span></p>
<p>Resolvendo para <span class="math inline">\(R\)</span>, temos</p>
<p><span class="math display">\[\begin{align*}
  R = P_0 \cdot r \cdot \left( \frac{(1+r)^T}{(1+r)^T-1}\right)
\end{align*}\]</span></p>
<hr>
<blockquote class="blockquote">
<p><em>0. Para cada <span class="math inline">\(t \in {0,1,\ldots,T}\)</span>, vale <span class="math inline">\(P_t = P_0 - tP_0/T\)</span>.</em></p>
</blockquote>
<p>Afirmação falsa, nós calcluamos <span class="math display">\[\begin{align*}
  P_t = (1+r)^tP_0-R\left(\frac{(1+r)^t-1}{r}\right)
\end{align*}\]</span></p>
<hr>
<blockquote class="blockquote">
<p><em>1. Cada prestação é de <span class="math inline">\(P_0(1+r)^T/T\)</span> reais.</em></p>
</blockquote>
<p>Afirmação também falsa, calculamos a prestação <span class="math inline">\(R\)</span> como <span class="math display">\[\begin{align*}
  R = P_0 \cdot r \cdot \left( \frac{(1+r)^T}{(1+r)^T-1}\right)
\end{align*}\]</span></p>
<hr>
<blockquote class="blockquote">
<p><em>2. Cada prestação supera os <span class="math inline">\(rP_0\)</span> reais.</em></p>
</blockquote>
<p>Essa afirmação é verdadeira. Intuitivamente, <span class="math inline">\(rP_0\)</span> é o juro acumulado sobre o principal <span class="math inline">\(P_0\)</span> entre <span class="math inline">\(t=0\)</span> e <span class="math inline">\(t=1\)</span>. Se a prestação fosse <span class="math inline">\(rP_0\)</span>, o saldo devedor <span class="math inline">\(P_t\)</span> se manteria constante no tempo e a dívida nunca seria quitada. Faça <span class="math inline">\(P_t=P_{t-1}\)</span>: <span class="math display">\[\begin{align*}
  P &amp;= (1+r)P-R \\
  P-P-rP &amp;= -R \\
  R &amp;= rP
\end{align*}\]</span></p>
<p>Conseguimos também ver isso diretamente da expressão para <span class="math inline">\(R\)</span>. Tome <span class="math display">\[\begin{align*}
  R = P_0 \cdot r \cdot \left( \frac{(1+r)^T}{(1+r)^T-1}\right)
\end{align*}\]</span> Agora multiplique por <span class="math inline">\((1+r)^{-T}/(1+r)^{-T}\)</span>. Ficamos com <span class="math display">\[\begin{align*}
  R = P_0 \cdot r \cdot \left( \frac{1}{1-(1+r)^{-T}}\right)
\end{align*}\]</span></p>
<p>Se <span class="math inline">\((1+r)&gt;1\)</span>, então <span class="math inline">\((1+r)^{-k}&lt;1\)</span>, para <span class="math inline">\(k=1,2,3,\dots\)</span>. Portanto <span class="math display">\[\begin{align*}
\left( \frac{1}{1-(1+r)^{-T}}\right) &gt; 1, \text{ e } R&gt;rP_0
\end{align*}\]</span></p>
<hr>
<blockquote class="blockquote">
<p><em>3. Quanto maior <span class="math inline">\(r\)</span>, maior será <span class="math inline">\(R\)</span>.</em></p>
</blockquote>
<p>Afirmação verdadeira. Claro que, fixada a duração <span class="math inline">\(T\)</span>, quanto maior a taxa de juros de um financiamento, maior será a parcela necessária para quitar o saldo devedor.</p>
<p>A rígor, deveríamos calcular <span class="math inline">\(dR/dr\)</span> e mostrar que se <span class="math inline">\(r&gt;0\)</span> e <span class="math inline">\(P_0&gt;0\)</span> então <span class="math inline">\(dR/dr&gt;0\)</span>.</p>
<hr>
<blockquote class="blockquote">
<p><em>4 Ao fim do período <span class="math inline">\(T/2\)</span>, o saldo devedor ainda corresponde a mais da metade da dívida inicial.</em></p>
</blockquote>
<p>Esse é, de longe, o item mais difícil da questão.</p>
<p>Se a afirmação é verdadeira, então</p>
<p><span class="math display">\[\begin{align*}
  P_{T/2} &gt; (1/2)P_0.
\end{align*}\]</span></p>
<p>Equivalentemente, se</p>
<p><span class="math display">\[\begin{align*}
  2\frac{P_{T/2}}{P_0}&gt;1.
\end{align*}\]</span></p>
<p>Ou, ainda,</p>
<p><span class="math display">\[\begin{align*}
  2\frac{P_{T/2}}{P_0}-1&gt;0.
\end{align*}\]</span></p>
<p>É a desigualdade acima que iremos julgar.</p>
<p>Agora lembre que, porque <span class="math inline">\(P_T=0\)</span>, sabemos que <span class="math inline">\(R=P_0\cdot r \cdot (1-(1+r)^{-T})^{-1}\)</span>. Esse é o valor da prestação fixa que zera o saldo devedor <span class="math inline">\(P_t\)</span> exatamente no período <span class="math inline">\(t=T\)</span>.</p>
<p>Substituindo na fórmula para <span class="math inline">\(P_t\)</span>, <span class="math display">\[\begin{align*}
  P_t = (1+r)^tP_0 - P_0\cdot r \cdot \left(\frac{(1+r)^T}{(1+r)^T-1}\right)\left(\frac{(1+r)^t-1}{r}\right)
\end{align*}\]</span></p>
<p>Depois de algumas manipulações conseguimos escrever</p>
<p><span class="math display">\[\begin{align*}
  \frac{P_t}{P_0} = \frac{(1+r)^T-(1+r)^t}{(1+r)^T-1}.
\end{align*}\]</span></p>
<p>Fazendo <span class="math inline">\(t=T/2\)</span> e multiplicando por <span class="math inline">\(2\)</span>,</p>
<p><span class="math display">\[\begin{align*}
  \frac{2P_{T/2}}{P_0} = 2\left(\frac{(1+r)^T-(1+r)^{T/2}}{(1+r)^T-1}\right).
\end{align*}\]</span></p>
<p>Chame <span class="math inline">\((1+r)^{T/2}=x\)</span></p>
<p><span class="math display">\[\begin{align*}
  \frac{2P_{T/2}}{P_0} &amp;= 2\left(\frac{x^2-x}{x^2-1}\right) \\
  &amp;= 2x \left(\frac{x-1}{(x+1)(x-1)}\right) \\
  &amp;= 2x \left(\frac{1}{x+1}\right)
\end{align*}\]</span></p>
<p>Então,</p>
<p><span class="math display">\[\begin{align*}
  \frac{2P_{T/2}}{P_0}-1 &amp;= 2x \left(\frac{1}{x+1}\right)-1 \\
  &amp;= \frac{2x-(x+1)}{x+1} = \frac{x-1}{x+1}
\end{align*}\]</span></p>
<p>Lembrando que a afirmação é verdadeira se <span class="math inline">\(\dfrac{2P_{T/2}}{P_0}-1&gt;0\)</span>, e que <span class="math inline">\(x=(1+r)^{T/2}&gt;1\)</span>. Como <span class="math inline">\(x&gt;1\)</span>, a desigualdade abaixo vale.</p>
<p><span class="math display">\[\begin{align*}
\frac{x-1}{x+1} &gt; 0
\end{align*}\]</span></p>
<p>Afirmação verdadeira.</p>
</div>
</div>
</div>
</div>
</section>
<section id="questão-10-anpec-2025-matemática" class="level3">
<h3 class="anchored" data-anchor-id="questão-10-anpec-2025-matemática">Questão 10 (ANPEC 2025 – Matemática)</h3>
<div id="exr-anpec-2025-matematica-Q10" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercício 3</strong></span> &nbsp;</p>
<blockquote class="blockquote">
<p>Tema: Equações em diferenças.</p>
</blockquote>
<p>Considere o contexto em que um investimento inicial de <span class="math inline">\(A&gt;0\)</span> unidades monetárias pode ser aplicado, no período inicial <span class="math inline">\(t=0\)</span>, em apenas um dentre dois ativos disponíveis.</p>
<p>O primeiro ativo remunera a uma taxa de juros <span class="math inline">\(r&gt;0\)</span> e, devido a custos operacionais, deduz do saldo um valor <span class="math inline">\(B_t\)</span> em cada período <span class="math inline">\(t=0,1,2,\ldots\)</span>. Ainda, dada uma aplicação inicial <span class="math inline">\(x_0\)</span> igual a <span class="math inline">\(A&gt;0\)</span>, o valor no instante <span class="math inline">\(t+1\)</span> satisfaz <span class="math inline">\(x_{t+1}=(1+r)x_t-B_t\)</span>, onde <span class="math inline">\(\forall t\geq 0\)</span>, <span class="math inline">\(B_{t+1}=\left(\frac{1+r}{2}\right)B_t\)</span> e <span class="math inline">\(B_0=\frac{A}{2}\)</span>.</p>
<p>Com respeito ao segundo ativo, uma mesma aplicação inicial <span class="math inline">\(y_0\)</span> em <span class="math inline">\(t=0\)</span> igual a <span class="math inline">\(A&gt;0\)</span> implica um valor <span class="math inline">\(y_{t+1}\)</span> no período <span class="math inline">\(t+1\)</span> que satisfaz <span class="math inline">\(y_{t+1}=(1+\bar r)y_t\)</span>, onde <span class="math inline">\(\bar r&gt;0\)</span>.</p>
<p>Sabendo que <span class="math inline">\(\frac{1+r}{1+\bar r}=V\geq 0\)</span> e <span class="math inline">\(\lim_{t\rightarrow\infty}\frac{x_t}{y_t}=\frac{1}{2}\)</span>, determine o valor de <span class="math inline">\(V\)</span>.</p>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Resolução">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Cuidado</span>Resolução
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[\begin{align*}
  B_1 &amp;= \left(\frac{1+r}{2}\right)B_0\\
  B_2 &amp;= \left(\frac{1+r}{2}\right)B_1 = \left(\frac{1+r}{2}\right)^2B_0
\end{align*}\]</span></p>
<p>Generalizando,</p>
<p><span class="math display">\[\begin{align*}
  B_t = \left(\frac{1+r}{2}\right)^tB_0
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  x_t = (1+r)x_{t-1}-B_{t-1}
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  x_t = (1+r)x_{t-1}-\left(\frac{1+r}{2}\right)^{t-1}B_0
\end{align*}\]</span></p>
<p>Com <span class="math inline">\((1+r)=a\)</span>, também, faça <span class="math inline">\((a/2)=q\)</span>.</p>
<p><span class="math display">\[\begin{align*}
  x_t = ax_{t-1}-q^{t-1}B_0
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  x_1 &amp;= ax_0-q^{1-1}B_0\\
  &amp;= ax_0-B_0
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  x_2 &amp;= ax_1 - B_1 \\
  &amp;= a(ax_0-B_0) - qB_0 \\
  &amp;= a^2x_0 - aB_0 - qB_0
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  x_3 &amp;= ax_2 - B_2 \\
  &amp;=  a(a^2x_0-aB_0-qB_0)-q^2B_0 \\
  &amp;= a^3x_0 - a^2B_0 - aqB_0 - q^2B_0
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  x_4 &amp;= ax_3 - B_3 \\
  &amp;= a(a^3x_0 - a^2B_0 - aqB_0 - q^2B_0) - q^3B_0 \\
  &amp;= a^4x_0 - (a^3 + a^2q + aq^2 + q^3)B_0
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  x_5 &amp;= ax_4 - B_4 \\
  &amp;= a^5 x_0 - B_0(a^4 + a^3q + a^2q^2 + aq^3 + q^4)
\end{align*}\]</span></p>
<p>Perceba que a expressão entre parênteses é</p>
<p><span class="math display">\[\begin{align*}
  S_n = \sum_{j=1}^n a^{n-j}q^j
\end{align*}\]</span></p>
<p>Faça <span class="math inline">\(a^{-n}S_n\)</span>:</p>
<p><span class="math display">\[\begin{align*}
  a^{-n}S_n = a^{-n}\sum_{j=0}^n a^{n-j}q^j=\sum_{j=0}^n a^{-j}q^j = \sum^n_{j=0}(q/a)^j
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  a^{-n}S_n &amp;= 1 + p + p^2 + \cdots + p^n \\
  pa^{-n}S_n &amp;= p + p + p^2 + \cdots + p^n + p^{n+1}
\end{align*}\]</span></p>
<p>Então</p>
<p><span class="math display">\[\begin{align*}
  a^{-n}S_n-pa^{-n}S_n = 1-p^{n+1} \\
  S_na^{-n}(1-p) = 1-p^{n+1}
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  S_n = a^n\left(\frac{1-p^{n+1}}{1-p}\right)
\end{align*}\]</span></p>
<p><span class="math display">\[\begin{align*}
  S_n = a^n\left(\frac{1-p^{n+1}}{1-p}\right)
\end{align*}\]</span></p>
<p>Mas <span class="math inline">\(q=a/2\)</span>, então</p>
<p><span class="math display">\[\begin{align*}
  p = \frac{a/2}{a/1} = 1/2
\end{align*}\]</span></p>
<p>E</p>
<p><span class="math display">\[\begin{align*}
  S_n &amp;= a^n \left( \frac{1-(1/2)^{n+1}}{1-1/2} \right) \\
  &amp;= 2a^n \left(2-(1/2)^{n+1}\right)
\end{align*}\]</span></p>
<p>Então</p>
<p><span class="math display">\[\begin{align*}
  x_t &amp;= a^tx_0 + B_0 S_{t-1} \\
  &amp;= a^t x_0 + B_0 a^{t-1}(1-(1/2)^n) \\
  &amp;= a^t x_0 + a^tB_0a^{-1}(1-(1/2)^n)
\end{align*}\]</span></p>
<p>E <span class="math inline">\(x_0=A\)</span> e <span class="math inline">\(B_0=A/2\)</span></p>
<p><span class="math display">\[\begin{align*}
  x_t &amp;= a^tA + a^t(A/2)a^{-1}(1-(1/2)^n) \\
  &amp; = \frac{2a^tA + a^tAa^{-1}(1-(1/2)^n)}{2}
\end{align*}\]</span></p>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="concursos-públicos" class="level2">
<h2 class="anchored" data-anchor-id="concursos-públicos">Concursos Públicos</h2>
<ul>
<li>Concurso Banco Central 2024, Cargo: Analista - Economia e Finanças.
<ul>
<li><a href="https://arq.pciconcursos.com.br/provas/33165042/5cc924e9beef/analista_Economia_e_financas.pdf">Link para a prova.</a></li>
<li><a href="https://arq.pciconcursos.com.br/provas/33165042/68c6775a2364/gabarito.pdf">Link para o gabarito oficial.</a></li>
</ul></li>
</ul>
<section id="questão-77-banco-central-2024-cargo-analista---economia-e-finanças" class="level3">
<h3 class="anchored" data-anchor-id="questão-77-banco-central-2024-cargo-analista---economia-e-finanças">Questão 77 (Banco Central 2024, Cargo: Analista - Economia e Finanças)</h3>
<div id="exr-bc-2024-Q77" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercício 4</strong></span> Acerca dos títulos emitidos pelo Tesouro Nacional, julgue os itens seguintes.</p>
<ol start="79" type="1">
<li>O valor investido no título Tesouro Prefixado 2031 pode ser resgatado a qualquer data, com a garantia da taxa de juros contratada no dia da compra.</li>
<li>O rendimento dos títulos Tesouro IPCA corresponde a uma taxa prefixada de juros somada à variação do índice nacional de preços ao consumidor amplo (IPCA) no período.</li>
</ol>
<p>No que se refere ao mercado de ações, julgue os itens a seguir.</p>
<ol start="81" type="1">
<li>O valor de mercado de uma ação coincide com o seu valor intrínseco, por corresponder às expectativas de fluxos de ganhos futuros.</li>
<li>Enquanto ações ordinárias dão direito apenas a voto, as ações preferenciais dão direito à parte dos dividendos proporcional ao número de votos detidos pelo acionista.</li>
</ol>
<p>Considerando que o preço de mercado de uma ação esteja em <strong>R$ 195,00</strong>, julgue o próximo item, referente ao mercado de opções.</p>
<ol start="83" type="1">
<li>No referido contexto, o titular de opções de venda da referida ação poderá vendê-la por <strong>R$ 200,00</strong> e, com isso, terá ganho igual a <strong>R$ 5,00</strong>, descontado o prêmio pago pelas opções.</li>
</ol>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Resolução">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Cuidado</span>Resolução
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p><em>79. O valor investido no título Tesouro Prefixado 2031 pode ser resgatado a qualquer data, com a garantia da taxa de juros contratada no dia da compra.</em></p>
</blockquote>
<p>Falso. É possível vender o Tesouro Prefixado antes do vencimento, mas sem garantia da taxa contratada — o preço oscila conforme as taxas de mercado (marcação a mercado).</p>
<hr>
<blockquote class="blockquote">
<p><em>80. O rendimento dos títulos Tesouro IPCA corresponde a uma taxa prefixada de juros somada à variação do índice nacional de preços ao consumidor amplo (IPCA) no período.</em></p>
</blockquote>
<p>Verdadeiro. O Tesouro IPCA rende taxa real prefixada + variação do IPCA do período.</p>
<hr>
<blockquote class="blockquote">
<p><em>81. O valor de mercado de uma ação coincide com o seu valor intrínseco, por corresponder às expectativas de fluxos de ganhos futuros.</em></p>
</blockquote>
<p>Falso. O preço de mercado de uma ação resulta de oferta e demanda e pode divergir do “valor intrínseco” (valor presente dos fluxos esperados). É formado pela expectativa conjunta dos agentes do mercado acerca dos fluxos futuros de dividendos.</p>
<hr>
<blockquote class="blockquote">
<p><em>82. Enquanto ações ordinárias dão direito apenas a voto, as ações preferenciais dão direito à parte dos dividendos proporcional ao número de votos detidos pelo acionista.</em></p>
</blockquote>
<p>Falso. Ações ordinárias têm direito a voto (e também a dividendos); ações preferenciais geralmente têm prioridade em dividendos e, em situações usuais, não têm direito voto na assembéia dos acionistas. Dividendos são proporcionais ao número de ações, não de votos.</p>
<hr>
<blockquote class="blockquote">
<p><em>Considerando que o preço de mercado de uma ação esteja em <strong>R$ 195,00</strong>, julgue o próximo item, referente ao mercado de opções.</em></p>
</blockquote>
<blockquote class="blockquote">
<p><em>83. No referido contexto, o titular de opções de venda da referida ação poderá vendê-la por <strong>R$ 200,00</strong> e, com isso, terá ganho igual a <strong>R$ 5,00</strong>, descontado o prêmio pago pelas opções.</em></p>
</blockquote>
<p>Verdadeiro. Se eu detenho uma opção de venda com strike <span class="math inline">\(K=200\)</span> e o preço de mercado da ação é <span class="math inline">\(S=195\)</span>, e eu exercer tal opção (o equivalente a vender minha ação ao emissor pelo preço <span class="math inline">\(K\)</span>), o resultado líquido é <span class="math inline">\(K-S=5\)</span>, não considerando o prêmio pago pela opção de venda.</p>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="certificações-anbima-cpa" class="level2">
<h2 class="anchored" data-anchor-id="certificações-anbima-cpa">Certificações Anbima CPA</h2>
<ul>
<li><a href="https://www.anbima.com.br/data/files/DF/86/EE/B6/EB6F8910C03A3F89B82BA2A8/Caderno-de-questoes-CPA.pdf">Link para fonte das questões</a></li>
</ul>
<section id="questão-2" class="level3">
<h3 class="anchored" data-anchor-id="questão-2">Questão 2</h3>
<div id="exr-anbima-CPA-Q02" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercício 5</strong></span> <strong>Contexto:</strong></p>
<p>Paulo pediu ao seu gerente duas opções de investimento com um horizonte de 360 dias para aplicar R$ 1.000,00. O gerente apresentou-lhe um CDB de instituição de grande porte com prazo de 1 ano e taxa de remuneração bruta de 12% a.a. A segunda opção foi um Certificado de Operações Estruturadas (COE) com exposição ao Índice Ibovespa (IBOV), também com prazo de 1 ano. O COE tem a seguinte estrutura de retornos:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 48%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th>Valor do IBOV em um ano</th>
<th>Valor retornado aos investidores em um ano</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Menor ou igual que 125.000</td>
<td>R$ 1.000,00</td>
</tr>
<tr class="even">
<td>Maior que 125.000 e abaixo ou igual que 145.000</td>
<td>1.000 * [1 + (IBOV − 125.000) / 125.000]</td>
</tr>
<tr class="odd">
<td>Acima de 145.000 e abaixo ou igual de 153.700</td>
<td>1.000 * [1,16 + 0,75 * (IBOV − 145.000) / 145.000]</td>
</tr>
<tr class="even">
<td>Acima de 153.700</td>
<td>1.000 * 1,205</td>
</tr>
</tbody>
</table>
<p><strong>Enunciado:</strong></p>
<p>Com base nos aspectos apresentados e nas características dos produtos, a análise correta sobre o investimento de Paulo é:</p>
<ol type="A">
<li>Para que o COE apresente remuneração bruta superior ao CDB, o índice deve atingir ou superar 140.000 pontos.</li>
<li>Caso o índice Ibovespa atinja 160.000 em um ano, a rentabilidade líquida de impostos do COE será de 17,425%.</li>
<li>A tributação do imposto de renda incidente sobre o retorno do COE é inferior àquele incidente sobre o CDB.</li>
<li>O COE, assim como o CDB, são produtos cobertos pelo Fundo Garantidor de Créditos (FGC).</li>
</ol>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Resolução">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Cuidado</span>Resolução
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Um Certificado de Depósito Bancário (CDB) é um tipo de investimento de renda fixa bastante popular no Brasil em que você “empresta” dinheiro para uma instituição bancária em troca de juros. Condições de remuneração (pré ou pós-fixado) e de liquidez dependem do acordo entre a instituição bancária emitente e o detentor do CDB. Os CDB são cobertos pelo FGC (fundo garantidor de crédito).</p>
<p>Um Certificado de Operações Estruturadas (COE) é um produto financeiro de renda fixa, cuja remuneração (similarmente a um derivativo) é contingente ao valor de um ou mais diferentes ativos. Esses ativos podem ser ações, moedas, taxas de juro, etc. É comum que um COE defina perdas e ganhos máximos frente bandas de variação do preço dos “ativos objeto”. Os COE não são cobertos pelo FGC.</p>
<p>A tributação IR de ambos CDB e COE segue a tabela regressiva abaixo.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 49%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Prazo do Investimento</th>
<th>Alíquota de IR sobre os Rendimentos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Até 180 dias</td>
<td>22,5%</td>
</tr>
<tr class="even">
<td>De 181 a 360 dias</td>
<td>20,0%</td>
</tr>
<tr class="odd">
<td>De 361 a 720 dias</td>
<td>17,5%</td>
</tr>
<tr class="even">
<td>Acima de 720 dias (mais de 2 anos)</td>
<td>15,0%</td>
</tr>
</tbody>
</table>
<hr>
<blockquote class="blockquote">
<p><em>A. Para que o COE apresente remuneração bruta superior ao CDB, o índice deve atingir ou superar 140.000 pontos.</em></p>
</blockquote>
<p>A rentabilidade bruta do CDB pré-fixado do enunciado é sempre 12% ao ano.</p>
<p>Se o Ibovespa atingir 140000 pontos, o valor retornado ao investidor pelo COE é</p>
<p><span class="math display">\[\begin{align*}
  R\$ 1000\times\left(1+\frac{140000-125000}{125000}\right)
\end{align*}\]</span></p>
<p>Precisamos fazer a divisão acima:</p>
<p><span class="math display">\[\begin{align*}
  140-125 = 15
\end{align*}\]</span> <span class="math display">\[\begin{align*}
  \frac{15}{125} &amp;= \frac{1}{10}\frac{150}{125}\\
  &amp;=\frac{1}{10}\frac{6}{5}\\
  &amp;=0{,}1\times 1{,}2=0{,}12
\end{align*}\]</span></p>
<p>Portanto o valor retornado ao investidor seria <span class="math display">\[\begin{align*}
  R\$ 1000\times(1+0{,}12) = R\$ 1120
\end{align*}\]</span></p>
<p>Calculando o retorno como <span class="math inline">\((S_1-S_0)/S_0\)</span> vemos que, se o índice Ibovespa atingir 140000 pontos, o retorno bruto do investidor é exatamente 12%.</p>
<p>Então se o índice Ibovespa superar 140000 pontos, a remuneração bruta do COE é superior à remuneração bruta do CDB. Mas se o índice Ibovespa atingir exatamente 140000 pontos, ambas remunerações são idênticas. Logo: <em>“Para que o COE apresente remuneração bruta <strong>superior</strong> ao CDB, o índice deve <strong>superar</strong> 140000 pontos.”</em></p>
<p>Eu diria que a afirmativa é falsa. No gabarito oficial essa afirmação é considerada correta.</p>
<hr>
<blockquote class="blockquote">
<p><em>B. Caso o índice Ibovespa atinja 160.000 em um ano, a rentabilidade líquida de impostos do COE será de 17,425%.</em></p>
</blockquote>
<p>Se o índice Ibovespa atingir 160.000 pontos ao final do ano, o valor bruto retornado ao investidor no COE é <span class="math inline">\(R\$1205\)</span>.</p>
<p>Como o prazo do investimento é 360 dias, a alíquota relevante é 20%.</p>
<p>Portanto o imposto pago seria</p>
<p><span class="math display">\[\begin{align*}
  (R\$1205-R\$1000)\times 0.2 = R\$41
\end{align*}\]</span></p>
<p>O rendimento líquido seria <span class="math inline">\(R\$1205-R\$41 = R\$1164\)</span>, resultando em um retorno líquido de <span class="math inline">\(16{,4}\%\)</span>. Afirmação falsa.</p>
<hr>
<blockquote class="blockquote">
<p><em>C. A tributação do imposto de renda incidente sobre o retorno do COE é inferior àquele incidente sobre o CDB.</em></p>
</blockquote>
<p>Afirmação falsa. Ambos os investimentos têm o mesmo prazo e mesma tabela de IR, a tributação é a mesma.</p>
<hr>
<blockquote class="blockquote">
<p><em>D. O COE, assim como o CDB, são produtos cobertos pelo Fundo Garantidor de Créditos (FGC).</em></p>
</blockquote>
<p>Afirmação falsa. Dentre esses ativos, apenas o CDB é coberto pelo FGC.</p>
</div>
</div>
</div>
</div>
</section>
<section id="questão-9" class="level3">
<h3 class="anchored" data-anchor-id="questão-9">Questão 9</h3>
<div id="exr-anbima-CPA-Q09" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercício 6</strong></span> Lucas é um investidor conservador que busca preservar seu capital enquanto ganha um retorno constante. Ele tem algumas economias e deseja investir em títulos públicos. Lucas está particularmente preocupado com a inflação e quer garantir que seu investimento mantenha seu poder de compra ao longo do tempo, mesmo no caso de uma disparada inflacionária.</p>
<p><strong>Enunciado</strong></p>
<p>Lucas buscou orientação de seu gerente, que, considerando seu perfil, sugeriu que ele investisse em:</p>
<ol type="A">
<li>NTN-B.</li>
<li>LTN.</li>
<li>CDB.</li>
<li>LCA.</li>
</ol>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Resolução">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Cuidado</span>Resolução
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Lucas busca “preservar seu capital enquanto ganha um retorno constante”, “investir em títulos públicos”, e “está particularmente preocupado com a inflação”.</p>
<p><a href="https://www.tesourodireto.com.br/produtos/nossos-produtos">Descrição dos títulos emitidos pelo Tesouro</a></p>
<hr>
<p>A NTN-B (Nota do Tesouro Nacional Série B), ou Tesouro IPCA+ com Juros Semestrais, é um título de renda fixa emitido pelo Tesouro nacional cuja remuneração é composta por uma parte pré-fixada (garantida no momento da compra), mais a variação do índice IPCA. Essa seria a indicação adequada.</p>
<hr>
<p>A LTN (Letra do Tesouro Nacional), ou Tesouro Prefixado, é um título pré-fixado zero-cupom. No momento da compra o detentor paga o PU (que depende da <em>yield to maturity</em> implícita) e no vencimento recebe o valor de face de R$1000. Não seria uma indicação adequada porque não protege contra a inflação.</p>
<hr>
<p>Certificados de Depósito Bancário (CDB) é um tipo de investimento de renda fixa bastante popular no Brasil em que você “empresta” dinheiro para uma instituição bancária em troca de juros. Condições de remuneração (pré ou pós-fixado) e de liquidez dependem do acordo entre a instituição bancária emitente e o detentor do CDB. Os CDB são cobertos pelo FGC (fundo garantidor de crédito). Não seria uma indicação adequada porque nem sempre sua remuneração é vínculada à inflação, e porque não é um título público.</p>
<hr>
<p>Letras de Crédito do Agronegócio são títulos de renda fixa emitidos por instituições privadas cujos recursos são redirecionados para crédito a atividades agrícolas. Atualmente as LCA são isentas de imposto de renda. Não seria uma indicação adequada porque nem sempre sua remuneração é vínculada à inflação, e porque não é um título público.</p>
</div>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>